### PR TITLE
v2.0.0

### PR DESCRIPTION
**Pull request by akiraveliara**
- no more libsodium, as discussed in #lib-discussion - we're using a proper binding lib now
- libopus.so for linux-x64

please for the love of god squash merge this, no one needs to see my commits

### CODE REVIEW

**Comment by Emzi0767** [comment]
Linux natives were originally excluded for a very good reason, Linux doesn't exist. You have distros with wildly different core components.

You can't bundle Linux natives because they just won't work outside of whatever distro they were compiled for.

**Comment by OoLunar** [comment]
> Linux natives were originally excluded for a very good reason, Linux doesn't exist. You have distros with wildly different core components.
> 
> You can't bundle Linux natives because they just won't work outside of whatever distro they were compiled for.

As a Linux user, I disagree with a large part of this. Distros are not their own OS', but packages installed on top of a slightly modified Linux Kernel. The reason why many packages can be easily "cross-compiled" for other distros is that it's the same code/output files packaged in a different format.

Additionally, the only hard requirement here is glibc which is in a large portion of distros. There is a musl implementation of dotnet available, which means I can modify the GH actions to include a musl build. The musl build is proven useful when Natives is running in an Alpine Docker image.

**Comment by akiraveliara** [comment]
For the record, glibc is also a hard dependency of the dotnet runtime on Linux

**Comment by OoLunar** [comment]
There has been a lot of discussion on the Discord regarding the Natives package, and we've come to the following conclusion:

On startup, check to see if the `DSharpPlus.VoiceNext.Natives` package is installed in the project.
- If it is, great! Use it.
- If not, check to see if the Sodium and Opus lib packages are installed on the OS.
  - If it is, great! Use it.
  - If not, throw a startup exception at the user, telling them to install either Natives as a Nuget dependency (which should work across all OS' and most archs) or install the native Sodium and Opus lib packages for their OS

**Comment by Emzi0767** [comment]
> For the record, glibc is also a hard dependency of the dotnet runtime on Linux

Wrong, as evidenced by Alpine which doesn't even support it. And glibc versions aren't always compatible.

**Comment by OoLunar** [comment]
> > For the record, glibc is also a hard dependency of the dotnet runtime on Linux
> 
> Wrong, as evidenced by Alpine which doesn't even support it. And glibc versions aren't always compatible.

Dotnet does support Alphine as demonstrated by my Dockerfile: https://github.com/OoLunar/Tomoe/blob/rewrite/DSP_3.0/Dockerfile (should be noted that `libstdc++` is installed not as a dependency to Dotnet, but as a dependency to Humanizer)

**Comment by Emzi0767** [comment]
> > Linux natives were originally excluded for a very good reason, Linux doesn't exist. You have distros with wildly different core components.
> > 
> > You can't bundle Linux natives because they just won't work outside of whatever distro they were compiled for.
> 
> As a Linux user, I disagree with a large part of this. Distros are not their own OS', but packages installed on top of a slightly modified Linux Kernel. The reason why many packages can be easily "cross-compiled" for other distros is that it's the same code/output files packaged in a different format.
> 
> Additionally, the only hard requirement here is glibc which is in a large portion of distros. There is a musl implementation of dotnet available, which means I can modify the GH actions to include a musl build. The musl build is proven useful when Natives is running in an Alpine Docker image.

And as someone who manages a fleet of assorted Linux servers, RHEL != RHEL != Debian != Ubuntu != Alpine != ..., I invite you to watch Linus Torvalds discuss this very subject. Many distros support more than 1 major version at a time, and they're not compatible. Debian has stable and oldstable, Ubuntu has Latest and LTS, CentOS had 7, 8, and stream. These were often incompatible within the same distro. With rolling release, you'll be broken more often than working. It's the very reason why docs instruct people to install the natives rather than use them. You'll notice that Linux builds of .NET components have per-distro RIDs more often than not as well.

**Comment by Emzi0767** [comment]
> > > For the record, glibc is also a hard dependency of the dotnet runtime on Linux
> > 
> > Wrong, as evidenced by Alpine which doesn't even support it. And glibc versions aren't always compatible.
> 
> Dotnet does support Alphine as demonstrated by my Dockerfile: https://github.com/OoLunar/Tomoe/blob/rewrite/DSP_3.0/Dockerfile (should be noted that `libstdc++` is installed not as a dependency to Dotnet, but as a dependency to Humanizer)

And Alpine is based on musl, doesn't even offer glibc (which is why I used a self-patched lavalink build for my bots).

**Comment by Emzi0767** [comment]
In summary: including Linux will be more harmful than beneficial.

**Comment by OoLunar** [comment]
Closed by f24bf1ea497bdf6d384c33e92e06aaca3956a3c1 and 9ed4c7746f3a33c900e09811a3a8e611f66de22d

**Pull request closed without merging**
